collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8834586
  brandStrength: 0.5386681
  lightness: 0.5085929
  brandColors:
    - '#5D5D5D'
    - '#B64125'
    - '#7BA092'
    - '#FFE7B3'
    - '#FAAD3B'
  rhythmicContrast: 0.367884
typography_spectrum: 0.7373791
layout_spectrum: 0
name: Quickstudios
